export const AUTH = 'AUTH'
export const LOGOUT = 'LOGOUT'
export const FETCH_SESSIONS = 'FETCH_SESSIONS'
export const CREATE_SESSION = 'CREATE_SESSION'
export const UPDATE_SESSION = 'UPDATE_SESSION'
export const DELETE_SESSION = 'DELETE_SESSION'

export const FETCH_ADDITIONAL_SESSION = 'FETCH_ADDITIONAL_SESSION'
export const CREATE_ADDITIONAL_SESSION = 'CREATE_ADDITIONAL_SESSION'
export const UPDATE_ADDITIONAL_SESSION = 'UPDATE_ADDITIONAL_SESSION'
export const DELETE_ADDITIONAL_SESSION = 'DELETE_ADDITIONAL_SESSION'

export const CREATE_TASK = 'CREATE_TASK'
export const FETCH_TASKS = 'FETCH_TASKS'

export const FETCH_QUERIES = 'FETCH_QUERIES'
export const CREATE_QUERY = 'CREATE_QUERY'
export const UPDATE_QUERY = 'UPDATE_QUERY'
export const DELETE_QUERY = 'DELETE_QUERY'

export const FETCH_WEBCODE = 'FETCH_WEBCODE'
export const CREATE_WEBCODE = 'CREATE_WEBCODE'
export const UPDATE_WEBCODE = 'UPDATE_WEBCODE'
export const DELETE_WEBCODE = 'DELETE_WEBCODE'

export const FETCH_WEBCODE_SUBMISSIONS = 'FETCH_WEBCODE_SUBMISSIONS'
export const CREATE_WEBCODE_SUBMISSIONS = 'CREATE_WEBCODE_SUBMISSIONS'

export const FETCH_CAPSTONE = 'FETCH_CAPSTONE'
export const CREATE_CAPSTONE = 'CREATE_CAPSTONE'
export const UPDATE_CAPSTONE = 'UPDATE_CAPSTONE'
export const DELETE_CAPSTONE = 'DELETE_CAPSTONE'

export const FETCH_CAPSTONE_SUBMISSION = 'FETCH_CAPSTONE_SUBMISSION'
export const CREATE_CAPSTONE_SUBMISSION = 'CREATE_CAPSTONE_SUBMISSION'

export const FETCH_LEAVES = 'FETCH_LEAVES'
export const CREATE_LEAVES = 'CREATE_LEAVES'
